# Generated by Django 4.2 on 2023-12-09 18:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="discount",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
