# Generated by Django 4.2 on 2024-12-04 21:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="price_purchase",
            field=models.DecimalField(decimal_places=2, default=None, max_digits=10),
        ),
    ]
