# Makefile

# Run Django development server
run:
	poetry run python manage.py runserver

# Make migrations
makemigrations:
	poetry run python manage.py makemigrations

# Apply migrations
migrate:
	poetry run python manage.py migrate

# Create a Django superuser
createsuperuser:
	poetry run python manage.py createsuperuser

seed_products:
	poetry run python manage.py seed_products
